### PR TITLE
Auto-compile in Cucumber

### PR DESCRIPTION
**Pull request by kevgo**
@charlierudolph @alexdavid 

implements @charlierudolph's brilliant idea in #23: run the transpiler automatically in Cucumber  before it starts.

If there is a transpilation error, it displays the transpiler error message and doesn't run the specs.

Unfortunately, Livescript doesn't export the [logic to compile files](https://github.com/gkz/LiveScript/blob/master/src/command.ls#L96), so I have to spin up a subshell here, which causes about a half-second delay. 

Once you guys approve this, I am going to extract this into https://github.com/originate/o-tools-livescript to make it reusable.

### CODE REVIEW

**Comment by alexdavid** [comment]
I don't like the idea of putting this in a hook in cucumber. Building for development might be different from building in CI for a production push. IMO this should be a script in `package.json` or a shell script in `bin/` that first runs build, and then runs `cucumber-js`.

**Comment by kevgo** [comment]
The big advantage is that I don't need to have `node_modules/.bin/watch` running in a separate terminal (which becomes a no-go with Tertestrial because of race conditions), and I don't need to use proprietary commands to run tests (like `bin/spec`) to run tests anymore. 

A CI server can (and should) still compile things the way it wants before deployment.

**Comment by alexdavid** [comment]
Why do you need to run watch if you have Tertestrial? Just have tertestrial configured to run `bin/feature` on save.

If the CI server compiles before running tests then the before hook of the tests will override the compilation, and if it compiles after then it will not test things in the same state as what gets pushed up to prod

**Comment by kevgo** [comment]
Hmm, good points. What would be an example where tests transpile differently than a CI server?

**Comment by alexdavid** [comment]
I could imagine a scenario where we want to minify & concatenate the source before pushing to npm. It shouldn't make a difference so for development I don't want it to take the extra time to do so, but to make sure there aren't any bugs I want CI to test the final source before pushing.

This is a contrived example, but it demonstrates my point which is running tests and building are separate actions and they shouldn't be combined except for development convenience, which can be done with a simple shell script.

**Comment by kevgo** [comment]
Makes sense. The downside of this is that it requires a proprietary test script. But well, given that we agreed some uniformity of test runners (just run 'bin/spec [<filename>]' in any repo) is nice, that's not really an argument here.

**Comment by kevgo** [comment]
Thanks for the very insightful conversation! Closing this in favor of #25

**Pull request closed without merging**
