### PR TITLE
Add link to emacs mode

### PR DESCRIPTION
**Pull request by dmh43**

### CODE REVIEW

**Comment by dmh43** [comment]
bump @kevgo

**Comment by kevgo** [comment]
Yes!!!  ✨🚀✨

**Comment by dmh43** [comment]
@kevgo doesn't look like I have write permissions to this repo

**Comment by kevgo** [comment]
Sorry about that! Fixed.

**Comment by dmh43** [comment]
@kevgo still cant push...

```
Pushing to git@github.com:Originate/tertestrial-server.git
Enter passphrase for key '/home/dany/.ssh/id_rsa': 
ERROR: Permission to Originate/tertestrial-server.git denied to dmh43.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kevgo** [comment]
Gaaa! Okay, fixed now for real!

**Comment by dmh43** [comment]
WOO!

**Comment by kevgo** [comment]
We finally got it in!!  👻

**Pull request closed without merging**
